let productos= [
    
    {nombre: "Funko Pop Batman", 
    foto: "/images/products/funko-batman.jpg", 
    descripcion: "Figura de Batman Funko Pop!", 
    franquicia: "Franquicia: DC",
    comentarios:"13 comentarios",
    id:0},
    
    {nombre: "Funko Pop Spider-Man", 
    foto: "/images/products/funko-spiderman.jpg", 
    descripcion: "Figura de Spider Man Funko Pop!", 
    franquicia: "Franquicia: Marvel",
    comentarios:"33 comentarios",
    id:1},
    
    {nombre: "Funko Pop Homero Simpson", 
    foto: "/images/products/funko-HomeroSimpson.jpg", 
    descripcion: "Figura de Homero Simpson Funko Pop!", 
    franquicia: "Franquicia: The Simpsons",
    comentarios:"45 comentarios",
    id:2},
    
    {nombre: "Funko Pop Harry Potter", 
    foto: "/images/products/funko-HarryPotter.jpg",
    descripcion: "Figura de Harry Potter Funko Pop!", 
    franquicia: "Franquicia: Harry Potter",
    comentarios:"10 comentarios",
    id:3},
    
    {nombre: "Funko Pop IT",
    foto: "/images/products/funko-it.jpg", 
    descripcion: "Figura de IT Funko Pop!",
    franquicia: "Franquicia: Craven",
    comentarios:"7 comentarios",
    id:4},
    
    {nombre: "Funko Pop Wonder Woman",
    foto: "/images/products/funko-wonderwoman.jpg", 
    descripcion: "Figura de Wonder Woman Funko Pop!", 
    franquicia: "Franquicia: DC",
    comentarios:"19 comentarios",
    id:5},
    
    {nombre: "Funko Pop Darth Vader",
    foto: "/images/products/funko-DarthVader.jpg",
    descripcion: "Figura de Darth Vader Funko Pop!",
    franquicia: "Franquicia: Start Wars",
    comentarios:"21 comentarios",
    id:6},
    
    {nombre: "Funko Pop Forrest Gump",
    foto: "/images/products/funko-ForestGump.jpg",
    descripcion: "Figura de Forest Gump Funko Pop!", 
    franquicia: "Franquicia: Landry's, Inc.",
    comentarios:"40 comentarios",
    id:7},
    
    {nombre: "Funko Pop Voldemort",
    foto: "/images/products/funko-Voldemort.jpg", 
    descripcion: "Figura de Voldemort Funko Pop!", 
    franquicia: "Franquicia: Harry Potter",
    comentarios:"100 comentarios",
    id:8},
    
    {nombre: "Funko Pop Winnie The Pooh",
    foto: "/images/products/funko-WinniethePooh.jpg", 
    descripcion: "Figura de Winnie The Pooh Funko Pop!", 
    franquicia: "Franquicia: Disney",
    comentarios:"99 comentarios",
    id:9},
    
    {nombre: "Funko Pop Iron Man",
    foto: "/images/products/funko-ironman.jpg", 
    descripcion: "Figura de Iron Man Funko Pop!", 
    franquicia: "Franquicia: Marvel",
    comentarios:"78 comentarios",
    id:10},
    
    {nombre: "Funko Pop Carl",
    foto: "/images/products/funko-Carl.jpg",
    descripcion: "Figura de Carl Funko Pop!", 
    franquicia: "Franquicia: Pixar",
    comentarios:"80 comentarios",
    id:11},    

    {nombre: "Funko Pop Mickey Mouse",
    foto: "/images/products/funko-mickey.jpg",
    descripcion: "Figura de Mickey Mouse Funko Pop!",
    franquicia: "Franquicia: Disney",
    comentarios:"58 comentarios",
    id:12},

    {nombre: "Funko Pop Genio",
    foto: "/images/products/funko-genio.jpg",
    descripcion: "Figura de Genio Funko Pop!",
    franquicia: "Franquicia: Disney",
    comentarios:"70 comentarios",
    id:13},

    {nombre: "Funko Pop Jack Sparow",
    foto: "/images/products/funko-Jacksparow.jpg",
    descripcion: "Figura de Jack Sparow Funko Pop!",
    franquicia: "Franquicia: Disney",
    comentarios:"44 comentarios",
    id:14},

    {nombre: "Funko Pop Hercules",
    foto: "/images/products/funko-Hercules.jpg",
    descripcion: "Figura de Hercules Funko Pop!",
    franquicia: "Franquicia: Disney",
    comentarios:"56 comentarios",
    id:15},
]
;

module.exports = productos;